name: 'Delete Spawn Data Image'
branding:
  color: purple
  icon: database
description: 'Delete a spawn data image'
inputs:
  dataImage: 
    description: 'The data image to delete'
    required: true
  additionalArgs:
    description: 'Additional arguments to provide (e.g flags for a command)'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dataImage }}
    - ${{ inputs.additionalArgs }}